#INICIADO SESIÓN COMO ROOT

CREATE ROLE 'gestor';

GRANT SELECT, INSERT, UPDATE, DELETE ON PracABD1.* TO 'gestor' WITH GRANT OPTION;
GRANT CREATE ROLE, DROP ROLE ON *.* TO 'gestor';
GRANT CREATE USER, ROLE_ADMIN ON *.* TO 'gestor';

CREATE USER 'gohan' IDENTIFIED BY 'gohan';

GRANT 'gestor' TO 'gohan';

SET DEFAULT ROLE ALL TO 'gohan';
